name: Docker image

on:
  push:
    branches: deploy
jobs:

  build:

    runs-on: realityfamilyVPS

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag realityfamily/dockervm:pandora-frontend && docker push realityfamily/dockervm:pandora-frontend